### PR TITLE
Update Course Title

### PR DESCRIPTION
**Pull request by tati**

### CODE REVIEW

**Comment by learykara** [comment]
don't forget to bump the version number :+1:

**Comment by learykara** [comment]
actually, I'm going to release something later today if you want to send both of those out under one version

**Comment by tati** [comment]
@learykara that would be awesome...gonna look at this locally one time and make sure it doesn't go to next line for justin real quick but should be good to go

**Comment by tati** [comment]
Jk justin needs this out asap because now the course page doesn't match the menu

**Pull request merged**
