### PR TITLE
Feature/high z index modal

### PR DESCRIPTION
**Pull request by benjaminEwhite**
Otherwise stuff below the modal appears above it :(

### CODE REVIEW

**Comment by learykara** [comment]
`100` seems a little high - is it really necessary to be that large?

**Comment by benjaminEwhite** [comment]
@learykara it's a guarantee that this will be on top. Think that's not bad practice, but correct me if i'm wrong.

**Comment by benjaminEwhite** [comment]
And i think, by definition, a modal should always be on top, no?

**Comment by learykara** [comment]
yeah, but I think it's best practice to make it as high as it needs to be without being excessively high. I remember being scolded once upon a time (I think by evan) for having unnecessarily high z-indexes -- @tholex care to weigh in?

**Comment by benjaminEwhite** [comment]
My thinking is that this is in Thinkful ui, so we don't really know what z-indexes will be in apps that use it. Setting it at 100 is a guarantee that it will always be higher than what is in any specific app. 

I mean, what constitutes high enough? 50? 25?

**Comment by learykara** [comment]
I believe the nav bar, which is on top of anything except a modal, is set at 10 -- but I'd have to double check

**Comment by benjaminEwhite** [comment]
@learykara that is correct. what do you think, should a modal appear above or below navbar?

**Comment by benjaminEwhite** [comment]
Vibrant discussion on z-index!

**Comment by learykara** [comment]
modal should be above -- so a z-index of 15 should be plenty ?

**Comment by benjaminEwhite** [comment]
You've got a deal!

**Comment by learykara** [comment]
:+1:

**Comment by tholex** [comment]
I thought the modal already had ~100 zindex. Sorry I didn't comment.

**Comment by tholex** [comment]
We can put some z-indexes into vars.less in the styleguide – variables like `z-modal`, `z-nav`, and if you want to put something above the modal you just say `z-index: @z-modal + 1;`

**Pull request merged**
